### PR TITLE
Resolve #569 Wrong implementation of ObservableSet.clear and Observab…

### LINKED ISSUE #569: Wrong implementation of ObservableSet.clear and ObservableList.clear
This issue is related to #568 .

The **clear** method of **ObservableList** and **ObservableSet** does this:

```Java

/* ObservableList */
@Override
public void clear() {
        if (observer != null) {
            observer.clear();
            for (E element : this) {
                observer.elementRemoved(element);
            }
        }
        list.clear();
}

/* ObservableSet */
@Override
public void clear() {
        if (observer != null) {
            observer.clear();
            for (E element : this) {
                observer.elementRemoved(element);
            }
        }
        set.clear();
}
```

This means that **clearing** an observable collection **where all the element where added**, results in those elements to be marked as **removed**, while instead **only those that where not previously added should result as removed**.

Because of the current implementation, this statement gives an error (and there might be other similar issues):

```Java

// Entity has a to-many relationship 'relatedEntities' to RelatedEntity

Entity entity = new Entity();
RelatedEntity relatedEntity = new RelatedEntity();
entity.getRelatedEntities().add(relatedEntity); // collection marks relatedEntity as 'added', which is correct
entity.getRelatedEntities().clear(); // collection marks relatedEntity as 'removed', which is NOT correct

getEntityDataStore().insert(entity); // This throws an exception, because it tries to remove the association between entity and related entity, that never existed
// io.requery.sql.RowCountException: Expected 1 row affected actual 0
// at io.requery.sql.EntityWriter.updateAssociation(EntityWriter.java:744)
// at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:634)
// at io.requery.sql.EntityWriter.insert(EntityWriter.java:444)
// at io.requery.sql.EntityWriter.insert(EntityWriter.java:402)
// at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:204)
// at io.requery.sql.EntityDataStore.insert(EntityDataStore.java:190)

```

### PR DESCRIPTION
**Pull request by mirkoluchi**
…leList.clear

Fix clear method and iterator

### CODE REVIEW

File: requery-test/src/test/java/io/requery/test/AbstractObservableCollectionTest.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import io.requery.util.ObservableCollection;
+
+import static junit.framework.TestCase.assertFalse;
+import static org.junit.Assert.assertTrue;
+
+/**
+ * Created by mluchi on 25/05/2017.
+ */
+
+public abstract class AbstractObservableCollectionTest<T extends Collection<Phone> & ObservableCollection<Phone>> {
```
Comment (npurushe) [inline requery-test/src/test/java/io/requery/test/AbstractObservableCollectionTest.java]: This can be changed to a ParameterizedTest, that way you don't need to subclass it

File: requery/src/main/java/io/requery/util/ObservableCollectionIterator.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+import java.util.Collection;
+import java.util.Iterator;
+
+import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
+
+
+/**
+ * Created by mluchi on 25/05/2017.
```
Comment (npurushe) [inline requery/src/main/java/io/requery/util/ObservableCollectionIterator.java]: you can use the `@author` tag instead

File: requery/src/main/java/io/requery/util/ObservableList.java [hunk 3]
```diff
@@ -194,17 +194,20 @@ public int lastIndexOf(Object o) {
...
-    @Override @Nonnull
+    @Override
+    @Nonnull
     public ListIterator<E> listIterator(int index) {
         return list.listIterator(index);
     }
 
-    @Override @Nonnull
+    @Override
+    @Nonnull
```
Comment (npurushe) [inline requery/src/main/java/io/requery/util/ObservableList.java]: Minor: these formatting changes should be omitted, since its unrelated

**Comment by mirkoluchi** [comment]
I made the requested changes.
